### ISSUE TITLE
Unity UI Examples not functioning 

### ISSUE THREAD

**Issue by lasvegasclick** [HoloLabInc/MRTKExtensionForNrealLight#2]
The MRTKExtensionForNrealLight works terrific in the emulator except for the Unity UI Examples. The components highlight when the cursor is over any element (such as the button and checkbox), but they do not respond to mouse clicks and the scroll doesn't work either. Have you experienced this behaviour?

**Comment by akihiro0105** [comment]
#3

**Comment by akihiro0105** [comment]
This issue is fixed at version v0.1.1.
